# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-15 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmdbPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_addr_ip', models.CharField(db_column='Inner_Addr_IP', max_length=32)),
                ('outer_addr_ip', models.CharField(blank=True, db_column='Outer_Addr_IP', max_length=32, null=True)),
                ('operating_system', models.CharField(blank=True, db_column='Operating_System', max_length=32, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=32, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=32, null=True)),
                ('available_zone', models.CharField(blank=True, db_column='Available_Zone', max_length=32, null=True)),
                ('cpu_info', models.IntegerField(blank=True, db_column='CPU_Info', null=True)),
                ('memory_info', models.IntegerField(blank=True, db_column='Memory_Info', null=True)),
                ('expire_time', models.DateTimeField(blank=True, db_column='Expire_Time', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='Create_Time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='Update_Time', null=True)),
            ],
            options={
                'db_table': 'cmdb_pool',
            },
        ),
    ]
