# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-15 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdbTreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('node_name', models.CharField(blank=True, max_length=32, null=True)),
                ('environment', models.CharField(blank=True, max_length=32, null=True)),
                ('service_info', models.TextField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('father_id', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='Create_Time', null=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_column='Update_Time', null=True)),
                ('node_type', models.CharField(blank=True, max_length=32, null=True)),
                ('tag', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'cmdb_tree_node',
            },
        ),
        migrations.AlterField(
            model_name='cmdbpool',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='Create_Time', null=True),
        ),
    ]
