# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20181215_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdbAnsibleSshInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_addr_ip', models.CharField(max_length=32)),
                ('outer_addr_ip', models.CharField(max_length=32)),
                ('ansible_ssh_user', models.CharField(max_length=32)),
                ('ansible_ssh_port', models.CharField(max_length=32)),
                ('ansible_sudo_pass', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cmdb_ansible_ssh_info',
            },
        ),
        migrations.CreateModel(
            name='CmdbProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=32)),
                ('develop', models.TextField(blank=True, null=True)),
                ('ops', models.TextField(blank=True, null=True)),
                ('test', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cmdb_product_info',
            },
        ),
    ]
