# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpsJobJobScriptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=32)),
                ('script_name', models.CharField(max_length=32)),
                ('script_content', models.TextField(default='')),
                ('drop_status', models.IntegerField(blank=True, default=0, null=True)),
                ('mTime', models.DateTimeField(auto_now=True, db_column='m_time', null=True)),
            ],
            options={
                'db_table': 'ops_job_job_script_info',
            },
        ),
        migrations.CreateModel(
            name='OpsJobScriptHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=32)),
                ('result', models.TextField(default='')),
                ('dtEventTime', models.DateTimeField(auto_now=True, db_column='dtEventTime', null=True)),
                ('exec_status', models.IntegerField(blank=True, default=0, null=True)),
                ('ip_list', models.TextField(default='')),
            ],
            options={
                'db_table': 'ops_job_script_history',
            },
        ),
    ]
