# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbJobDbInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_master', models.CharField(db_column='db_master', max_length=32)),
                ('db_slave', models.CharField(db_column='db_slave', max_length=32)),
                ('db_product', models.CharField(db_column='db_product', max_length=32)),
                ('db_product_id', models.CharField(db_column='db_product_id', max_length=32)),
                ('db_env', models.CharField(db_column='db_env', max_length=100)),
                ('db_mark', models.CharField(db_column='db_mark', max_length=100)),
                ('db_passwd', models.CharField(db_column='db_passwd', max_length=32)),
                ('db_container_name', models.CharField(db_column='db_container_name', max_length=100)),
                ('db_container_name_slave', models.CharField(db_column='db_container_name_slave', default='', max_length=100)),
                ('db_user_name', models.CharField(db_column='db_user_name', max_length=32)),
                ('db_service_type', models.CharField(db_column='db_service_type', default='container', max_length=32)),
                ('db_service_name', models.CharField(db_column='db_service_name', default='', max_length=32)),
                ('db_service_name_slave', models.CharField(db_column='db_service_name_slave', default='', max_length=100)),
            ],
            options={
                'db_table': 'db_job_db_instance',
            },
        ),
    ]
